### ISSUE TITLE
[RAI] Prerelease: Auxiliary Free Attack Clarification

### ISSUE THREAD

**Issue by SteamNinja** [AshleyMoni/Lancer-Community-Edition#219]
**The Problem:**
The Auxiliary (Size) tag in the Gear Tags section is lacking mention of the Skirmish and Barrage actions and reads as a separate rule from the restrictions used in Skirmish and Barrage in the combat section. 

Current text: "The smallest weapon size for mechs, can be fired if another weapon on the
same mount is fired but can’t benefit from bonus damage if fired this way."

**The Solution:**
Suggestion for possible clarified text: "The smallest weapon size for mechs, **during a skirmish or barrage** can be fired if another weapon on the
same mount is fired but can’t benefit from bonus damage if fired this way."

**The Location:**
Page 127

**Comment by lenaleciel** [comment]
Fixed in November Release, with the definition in the Gear Tags section on page 104 clarifying Skirmish and Barrage, and the initial introduction of weapon sizes on page 33 not mentioning any rules effects for weapon sizes at all, mostly just being a general fluff description of size as... physical size.
