### ISSUE TITLE
[Typo] November Release: Incorrect Table of Contents bookmark links

### ISSUE THREAD

**Issue by nice2835** [AshleyMoni/Lancer-Community-Edition#392]
**The Problem:**
Many of the clickable links in the pdf's ToC go to the wrong page. All mechs direct to Pegasus (makes sense though, it does know everything.)
**The Solution:**
Go through the ToC again and try to fix the links to go to the right page. Some are correct, some aren't.

**The Location:**
Page 4-5

**Comment by gapb** [comment]
It's a bit weirder than that. If you open the PDF in something that will show you the boundaries of a link, you'll see otherwise invisible rectangles on top of the otherwise correct ToC links that prevent you from clicking on them.

- The link to the Character Creation example on the first page of the ToC stretches from the "p. 36" to cover the entirety of Section 2.
- The link to the Pegasus on the second page covers a thin rectangle between the two columns, neatly obscuring the links to the other mechs.
- The link to the Vehicle rules on the third ToC page, much as the Character Creation example, obscures most of the links to Section 6.
- (The SSC mech header has a similar issue, but I didn't notice it until just now.)

Note: this is the BackerKit PDF; I have no idea if the itch.io one has the same problem.

<img width="1552" alt="Screen Shot 2019-11-28 at 3 47 42 PM" src="https://user-images.githubusercontent.com/723926/69834249-92c17380-11f6-11ea-8e3b-a16916b85c79.png">
<img width="1552" alt="Screen Shot 2019-11-28 at 3 48 19 PM" src="https://user-images.githubusercontent.com/723926/69834250-935a0a00-11f6-11ea-99b0-b92d9c4d6d9d.png">

**Comment by KaiTave** [comment]
I believe this has been fixed as of the latest version, please double check and post a new ticket if there are still outstanding errors.
