### ISSUE TITLE
[RAI] November Release: Tokugawa Overclock Clarifications

### ISSUE THREAD

**Issue by no-space** [AshleyMoni/Lancer-Community-Edition#630]
**The Problem:**
The Tokugawa's Overclock ability is unclear about when the bonuses are/can be triggered, how long they last, and what happens if the player is already exposed

**The Solution:**
Do the bonuses last until the end of the next turn, or until all Exposed states are cleared?

Do the Overclock bonuses apply whenever a character is exposed, like Limit Break, or only when the protocol is specifically activated?

If the character is already exposed, can they still activate the protocol? Can this result in potentially clearing exposed early, or is it tracked separately to exposed states from other sources?

What happens if the character becomes exposed from another source before the Overclock exposed state ends?

If you can activate the protocol while already exposes, could the character activate the protocol two turns in a row? It's not specified that the bonuses are non-stackable.

For reference, PRv2 had Overclock bonuses trigger automatically during the relevant state

**The Location:**
Page 250

**Comment by KaiTave** [comment]
As far as I am aware, the Overclock bonuses specifically are only meant to apply when that protocol is activated, not when the Tokugawa is exposed through other means. As for the rest, clarification by the developers would be helpful.

Re: "If the character is already exposed, can they still activate the protocol? Can this result in potentially clearing exposed early, or is it tracked separately to exposed states from other sources?" My suggestion for clarification in this regard would be for Overclock to state ""You become EXPOSED until the end of your next turn **if you are not already EXPOSED.**" This way if a character is already Exposed from another source, that one and its associated timing takes precedence including when it may be cleared.

**Comment by lenaleciel** [comment]
If one is intentionally allowed to activate the protocol while already Exposed in order to get the Range/Threat bonuses, then there is little functional difference to just wrapping the bonuses into Limit Break, as a sort of "Well, I'm already Exposed, this can't hurt" sort of deal, as you would have little reason to not activate it whenever you would be already Exposed by outside sources. 

Doing so would additionally allow you to dodge the question of "If you Overclock once and then Overclock on the next turn, do you get double the range bonus?" as it would be a conditional state, as well as letting you remove the energy weapon requirement for the range boost because your weapons would be dealing energy damage anyways from the other effects of Limit Break.

You'd have to rewrite the stacking clause of Radiance though.

**Comment by KaiTave** [comment]
I think rather than wrapping it into the Limit Break trait itself Overclock could simply state "While Exposed, all weapons on your mech that deal any energy damage gain +5 range if they are ranged weapons or gain +1 threat if they are melee weapons." if the intent is for the bonus to apply whenever the Tokugawa is exposed regardless of source. If that's NOT the case then you could simply add a "this bonus does not stack with itself" clause to the Overclock protocol.

**Comment by lenaleciel** [comment]
The range/threat increase has been wrapped into Limit Break, and Overclock just Exposes you now, which should clear up everything here.
