### ISSUE TITLE
[RAI] December Release - The cost of jumping

### ISSUE THREAD

**Issue by Dokujaka** [AshleyMoni/Lancer-Community-Edition#667]
**The Problem:**
In the section about jumping it is not immediately clear what the cost of jumping is, only the limits to length/height.

**The Solution:**
A simple clause about how much of your movement it costs to jump.

**The Location:**
Page 63

**Comment by Jay-Iles** [comment]
First paragraph of Jumping replaced with:
"Characters with legs can jump instead of their standard move. They may jump horizontally, moving half their speed in a straight line and ignoring obstructions at ground level that they could jump over (such as pits or gaps), or they may can jump vertically, moving 1 space adjacent and moving up by spaces equivalent to their Size. For example, a Size 1 mech could jump up to 1 space high, and 1 space over. Characters that jump and end the jump mid air automatically fall at the end of the move."
