### ISSUE TITLE
[RAI] December Release: Drone Commander III / Invigorate Clarifications

### ISSUE THREAD

**Issue by dwarf74** [AshleyMoni/Lancer-Community-Edition#716]
**The Problem:**
Confusing wording 
(1) Does the ally you're using for the Line get the benefits of the energy pulse?
(1a) If not, what if its point is used to extend to another allied unit?
(2) Can you extend the line with the first Quick action to other units, or does it require more Quick actions?
(3) Do hostile characters get a save vs. the 4 Energy damage?

**Comment by VertigoCharades** [comment]
For immediate concerns:
1. Yes.
1.a. Even if it didn't, extending the line to another unit could catch others in the resulting lines.
2. All of these lines are done effectively at once with your single quick action. You otherwise arguably wouldn't be able to extend the line, as you'd be activating the same system more than once in a given turn (page 71: "You can **ACTIVATE** any number of times a turn but can’t **ACTIVATE** the same system more than once unless you can do so as a free action.")
3. No save; assume that it'd be specific if a save was required.

The only possible ambiguity I spot is whether each line includes the target ally; I believe it should be, but I can believe that some may read "**LINE** to them" as non-inclusive of the target. I'm gonna add a separate tracker item for the missing RANGE icons though.

**Comment by KaiTave** [comment]
I'll leave this ticket open for the moment until Jay or Melody close it, but VertigoCharades' assessment of all of these questions is correct.

**Comment by Jay-Iles** [comment]
How's this as a clarification:
"As a quick action, you may send a pulse of energy to an allied character (including Drones) within range 3, drawing a Line to them. You may extend the pulse from your target to another allied character, extending the Line to them, as long as they are within range 3, and you may continue extending the pulse (and Line) like this as long as you don’t target the same character twice. Allied characters who are used as pulse targets or are in the Line’s path gain 4 Overshield; hostile characters in the Line’s path take 4 energy damage instead."
