### ISSUE TITLE
[RAI] December Release - More jump confusion

### ISSUE THREAD

**Issue by Dokujaka** [AshleyMoni/Lancer-Community-Edition#717]
**The Problem:**
As it stands now, if you jump down a building, or indeed jump straight up in the air, you're stuck and can no longer move because you do not fall until the end of a turn. This leads to weird situations where a player can get stuck and essentially waste their entire movement.

**The Solution:**
Allowing players to fall at any point on their own turn would be a potential solution though a dev should probably clarify (or leave it as is I suppose).

**The Location:**
Page 63

**Comment by Jay-Iles** [comment]
Jumping first paragraph now:
"Characters with legs can jump instead of their standard move. They may jump horizontally, moving half their speed in a straight line and ignoring obstructions at ground level that they could jump over (such as pits or gaps), or they may can jump vertically, moving 1 space adjacent and moving up by spaces equivalent to their Size. For example, a Size 1 mech could jump up to 1 space high, and 1 space over. Characters that jump and end the jump mid air automatically fall at the end of the move."
