### ISSUE TITLE
[RAI] December Release: Grease Monkey's Machine Bond and Self-inflicted Conditions

### ISSUE THREAD

**Issue by lenaleciel** [AshleyMoni/Lancer-Community-Edition#776]
**The Problem:**
As written, rank II of Grease Monkey lets you clear self-inflicted conditions. In all likelihood, this is not intended, as most effects like this have been amended by Tom to specify that you can't clear self-inflicted ones.

**The Solution:**
Check with Tom to see if this is intentional, and add a clause specifying you can't clear a self-inflicted one, like in Stabilize.

**The Location:**
pg. 96 Machine Bond (Grease Monkey II)

**Comment by KaiTave** [comment]
I will say that I am 100% confident that it is NOT intentional, Tom has been very clear that self-inflicted conditions cannot be cleared ever, period. If additional clarity is desired, my suggestion would be to word the talent "When you STABILIZE, you clear all IMPAIRED, JAMMED, IMMOBILIZED, SLOWED, and LOCK ON conditions that weren’t caused by one of your own systems, talents, etc."

**Comment by Jay-Iles** [comment]
Machine bond now stats: "When you Stabilize, you clear all Impaired, Jammed, Immobilized, Slowed, and Lock On conditions that weren’t caused by your own systems, talents, etc."
